{{- if .Values.argoWorkflowsEnabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-event-role
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - patch
      - create
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-event-role
subjects:
  - kind: ServiceAccount
    name: event-stop
    namespace: argo-workflows
  - kind: ServiceAccount
    name: event-deploy
    namespace: argo-workflows
roleRef:
  kind: Role
  name: argo-event-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}