{{- range $configMap := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMap.name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
data:
{{- range $configMapItem := $configMap.items }}
  {{ $configMapItem.name }}: {{ $configMapItem.value | toYaml | nindent 4 }}
{{- end }}
{{- end }}