{{- range $item := .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $item.k8sSecretName }}
spec:
  secretStoreRef:
    name: {{ $.Release.Namespace }}-{{ $.Values.metadata.argoApplicationName }}-templated
    kind: SecretStore
  refreshInterval: 300s
  target:
    name: {{ $item.k8sSecretName }}
    template:
      type: {{ $item.k8sSecretType | default "Opaque" | quote }}
  data:
  {{- range $secretKey := $item.secretKeys }}
    - secretKey: {{ $secretKey.secretKey }}
      remoteRef:
        key: {{ $secretKey.key }}
        property: {{ $secretKey.property }}
  {{- end }}
{{- end }}
