{{ if eq $.Values.ingressType "nginx" }}
  {{- range $item_name, $item := .Values.pods }}
    {{- range $itemPorts := $item.ports }}
      {{- if $itemPorts.domains }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $item_name }}
  namespace: {{ $.Release.Namespace }}
spec:
  rules:
        {{- range $indexDomain, $domain := $itemPorts.domains }}
    - host: {{ $domain }}
      http:
        paths:
          {{- range $indexPath, $path := $itemPorts.paths }}
          - backend:
              service:
                name: {{ $item_name }}
                port:
                  number: {{ $itemPorts.port }}
            path: {{ $path }}
            pathType: Prefix
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}