{{- range $item := .Values.pods }}
{{- if $item.podDisruptionBudgetEnabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $item.name }}
  labels:
    app.kubernetes.io/name: {{ $item.name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $item.name }}
{{- end }}
{{- end }}