{{- range $item_name, $item := .Values.deployments }}
{{- if $item.podDisruptionBudgetEnabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $item_name }}
  labels:
    app.kubernetes.io/name: {{ $item_name }}
  namespace: {{ $.Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $item_name }}
{{- end }}
{{- end }}