{{- range $item_name, $item := .Values.deployments }}
{{- range $itemVolumes := $item.volumes }}
{{ if eq $itemVolumes.type "pvc" }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $itemVolumes.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/disk/{{ $itemVolumes.name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $itemVolumes.name }}
  labels:
    app.kubernetes.io/name: {{ $itemVolumes.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end }}
{{- end }}
{{- end }}
