{{- range $item_name, $item := .Values.pods }}
{{- range $itemVolumes := $item.volumes }}
{{ if eq $itemVolumes.type "longhorn" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $itemVolumes.name }}
  labels:
    app.kubernetes.io/name: {{ $itemVolumes.name }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "longhorn"
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ if $itemVolumes.size }}{{ $itemVolumes.size }}{{ else }}1Gi{{ end }}
{{- end }}
{{- end }}
{{- end }}
