{{- range $item_name, $item := .Values.pods }}
{{- range $itemVolumes := $item.volumes }}
{{ if eq $itemVolumes.type "vultr-hdd" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $itemVolumes.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $itemVolumes.name }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "vultr-block-storage-hdd"
spec:
  storageClassName: vultr-block-storage-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ if $itemVolumes.size }}{{ $itemVolumes.size }}{{ else }}40Gi{{ end }}
{{- end }}
{{- end }}
{{- end }}
