{{- range $item_name, $item := .Values.pods }}
{{- range $itemVolumes := $item.volumes }}
{{ if eq $itemVolumes.type "openebs-hostpath" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $itemVolumes.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $itemVolumes.name }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "openebs-hostpath"
spec:
  storageClassName: csi-s3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ if $itemVolumes.size }}{{ $itemVolumes.size }}{{ else }}1Gi{{ end }}
{{- end }}
{{- end }}
{{- end }}
