{{- range $item := .Values.pods }}
{{- range $itemVolumes := $item.volumes }}
{{ if eq $itemVolumes.type "vultr-hdd-retain" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $itemVolumes.name }}
  labels:
    app.kubernetes.io/name: {{ $itemVolumes.name }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "vultr-block-storage-hdd-retain"
    argocd.argoproj.io/sync-wave: "4"
spec:
  storageClassName: vultr-block-storage-hdd-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
{{- end }}
{{- end }}
{{- end }}
