{{- range $item_name, $item := .Values.pods }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $item_name }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: empty-role
subjects:
  - kind: ServiceAccount
    name: {{ $item_name }}
    namespace: {{ $.Release.Namespace }}
{{- end }}