{{- range $item_name, $item := .Values.pods }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $item_name }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $item_name }}
subjects:
  - kind: ServiceAccount
    name: {{ $item_name }}
    namespace: {{ $.Release.Namespace }}
  {{- range $saName, $sa := $item.extraServiceAccounts }}
  - kind: ServiceAccount
    name: {{ $saName }}
    namespace: {{ $sa.namespace }}
  {{- end }}
{{- end }}