{{- range $item_name, $item := .Values.deployments }}
  {{- if not $item.rbacDisabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $item_name }}
  namespace: {{ $.Release.Namespace }}
rules: {{- if $item.roleRules }} {{ $item.roleRules | toYaml | nindent 2 }}{{ else }} []{{ end }}
  {{- end }}
{{- end }}
