{{- range $item_name, $item := .Values.deployments }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{- if $item.serviceAccountName }} {{ $item.serviceAccountName }}{{ else }} 'default'{{- end }}
  namespace: {{ $.Release.Namespace }}
{{- end }}