{{- range $item_name, $item := .Values.pods }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{- if $item.serviceAccountName }} {{ $item.serviceAccountName }}{{ else }} {{ $item_name }}{{- end }}
  namespace: {{ $.Release.Namespace }}
{{- end }}