{{- range $item_name, $item := .Values.pods }}
{{- if $item.serviceAccountEnabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $item_name }}
  namespace: {{ $.Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $item_name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ $item_name }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}