{{- range $item := .Values.pods }}
  {{- range $itemPort := $item.ports }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ $item.name }}
{{- if $item.serviceMonitorEnabled }}
    app.kubernetes.io/part-of: kube-prometheus
{{- end }}
  name: {{ $item.name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  ports:
    - name: {{ $itemPort.name }}
      port: {{ $itemPort.port }}
      protocol: TCP
      targetPort: {{ $itemPort.port }}
  selector:
    app.kubernetes.io/name: {{ $item.name }}
  type: ClusterIP
status:
  loadBalancer: {}
    {{- if $item.oauth2 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ $item.name }}-oauth2
  name: {{ $item.name }}-oauth2
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  ports:
    - name: http-oauth2
      port: 4181
      protocol: TCP
      targetPort: 4181
  selector:
    app.kubernetes.io/name: {{ $item.name }}
  type: ClusterIP
status:
  loadBalancer: {}
    {{- end }}
  {{- end }}
{{- end }}