{{- range $item_name, $item := .Values.pods }}
  {{- if $item.ports }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ $item_name }}
  name: {{ $item_name }}
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
  {{- range $itemPort := $item.ports }}
    - name: {{ $itemPort.name }}
      port: {{ $itemPort.port }}
      protocol: TCP
      targetPort: {{ $itemPort.port }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ $item_name }}
  type: ClusterIP
status:
  loadBalancer: {}
  {{- end }}
{{- end }}