{{- range $item_name, $item := .Values.deployments }}
  {{- if $item.ports }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ $item_name }}
  name: {{ $item_name }}
  namespace: {{ $.Release.Namespace }}
spec:
    {{- if $item.serviceExternalName }}
  type: ExternalName
  externalName: {{ $item.serviceExternalName }}
    {{- else }}
  type: ClusterIP
  ports:
      {{- range $itemPort := $item.ports }}
    - name: {{ $itemPort.name }}
      port: {{- if $itemPort.portIngress }} {{ $itemPort.portIngress }}{{ else }} {{ $itemPort.port }}{{- end }} 
      protocol: TCP
      targetPort: {{ $itemPort.port }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ $item_name }}
    {{- end }}
  {{- end }}
{{- end }}