{{- range $item := .Values.pods }}
  {{- range $itemPorts := $item.ports }}
    {{- if $itemPorts.domains }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $item.name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host({{- $lastDomain := sub (len $itemPorts.domains) 1 }}{{- range $indexDomain, $domain := $itemPorts.domains }}`{{ $domain }}`{{ if ne $indexDomain $lastDomain }},{{ end }}{{- end }}) && PathPrefix({{- $lastPath := sub (len $itemPorts.paths) 1 }}{{- range $indexPath, $path := $itemPorts.paths }}`{{ $path }}`{{ if ne $indexPath $lastPath }},{{ end }}{{- end }})
      kind: Rule
      services:
        - name: {{ $item.name }}
          port: {{ $itemPorts.port }}
      {{- if or ($itemPorts.auth) ($item.oauth2) }}
      middlewares:
        - name: {{ $item.name }}-{{ $itemPorts.name }}
          namespace: {{ $.Values.namespace }}
      {{- end }}
      {{- if $itemPorts.auth }}
        {{ if $item.oauth2 }}
---
        {{ else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ $item.name }}-{{ $itemPorts.name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
data:
  users: {{ $itemPorts.auth }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}