{{- range $item := .Values.pods }}
{{- range $itemVolumes := $item.volumes }}
{{ if eq $itemVolumes.type "nfs" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $itemVolumes.name }}
  labels:
    app.kubernetes.io/name: {{ $itemVolumes.name }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "sys-truenas-nfs"
spec:
  storageClassName: sys-truenas-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end }}
{{- end }}
{{- end }}
