{{- range $item := .Values.pods }}
{{ if $item.oauth2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth2
  namespace: {{ $.Values.namespace }}
data:
  PROVIDERS_OIDC_CLIENT_SECRET: "{{ .Values.oauthClient }}"
  SECRET: "{{ .Values.oauthSecret }}"
type: Opaque
{{- end }}
{{- end }}