{{- if .Values.secretRegistry }}
apiVersion: v1
kind: Secret
metadata:
  name: secrets-registry
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: "{{ .Values.secretRegistry }}"
type: kubernetes.io/dockerconfigjson
{{ end }}