{{- range $item := .Values.pods }}
{{ if $item.oauth2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth2
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
data:
  PROVIDERS_OIDC_CLIENT_SECRET: "{{ $.Values.oauthClient }}"
  SECRET: "{{ $.Values.oauthSecret }}"
type: Opaque
{{- end }}
{{- end }}