{{- if .Values.secretRegistry }}
apiVersion: v1
kind: Secret
metadata:
  name: secrets-registry
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
data:
  .dockerconfigjson: "{{ .Values.secretRegistry }}"
type: kubernetes.io/dockerconfigjson
{{ end }}